line_length:
    warning: 160
    error: 180
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 150
    error: 200
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 200
    error: 300
file_length:
    warning: 300
    error: 500
    ignore_comment_only_lines: true

opt_in_rules:
- opening_brace
- trailing_semicolon
- toggle_bool
- cyclomatic_complexity
- type_name
- unneeded_parentheses_in_closure_argument
- yoda_condition
- unavailable_function
- nesting
- anyobject_protocol
- array_init
- closure_end_indentation
- closure_spacing
- attributes
- empty_count
- empty_string
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- explicit_init
- fallthrough
- first_where
- implicit_return
- private_action
- private_outlet
- multiline_function_chains
- multiline_parameters
- line_length
- override_in_extension
- overridden_super_call
- identical_operands
- lower_acl_than_parent
- multiline_arguments
- number_separator
- operator_usage_whitespace
- pattern_matching_keywords
- sorted_first_last
- sorted_imports
- prohibited_super_call
- redundant_nil_coalescing
- single_test_class
- weak_delegate
- function_default_parameter_at_end
- large_tuple
- discouraged_optional_boolean
- discouraged_optional_collection
- literal_expression_end_indentation
- no_extension_access_modifier
- identifier_name
- trailing_whitespace
- switch_case_alignment
- trailing_comma
- joined_default_parameter
- trailing_newline
- implicitly_unwrapped_optional
- return_arrow_whitespace
- syntactic_sugar
- comma
- colon
- force_cast
- force_try
- force_unwrapping

disabled_rules:
- todo
- private_over_fileprivate
- let_var_whitespace

