name: Archive

on:
  push:
    branches:
    - master

jobs:
  archive:
    runs-on: macOS-latest
    steps:
    - name: Check Out Sources
      uses: actions/checkout@v1
    - name: Create Archive
      run: xcodebuild build docbuild
                      -project Engine.xcodeproj
                      -scheme Engine archive 
                      -derivedDataPath /tmp/engine-build
                      -configuration Release
    - name: Upload the framework
      uses: actions/upload-artifact@v3
      with:
        name: Engine.framework
        path: /tmp/engine-build/Build/Products/Release/Engine.framework
    - name: Upload the documentation
      uses: actions/upload-artifact@v3
      with:
        name: Engine.doccarchive
        path: /tmp/engine-build/Build/Products/Release/Engine.doccarchive/
