name: Archive

on:
  push:
    branches:
    - master

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  archive:
    needs: tests
    runs-on: macOS-latest
    steps:
    - name: Check Out Sources
      uses: actions/checkout@v1
    - name: Build the project
      run: xcodebuild build docbuild
                      -project Engine.xcodeproj
                      -scheme Engine archive 
                      -derivedDataPath /tmp/engine-build
                      -configuration Release
    - name: Archive the documentation directory
      working-directory: /tmp/engine-build/Build/Products/Release
      run: tar -czf Engine.doccarchive.tar.gz Engine.doccarchive
    - name: Upload the framework
      uses: actions/upload-artifact@v3
      with:
        name: Engine.framework
        path: /tmp/engine-build/Build/Products/Release/Engine.framework
    - name: Upload the documentation
      uses: actions/upload-artifact@v3
      with:
        name: Engine.doccarchive.tar.gz
        path: /tmp/engine-build/Build/Products/Release/Engine.doccarchive.tar.gz
