name: SwiftLint

on:
  workflow_call:
  pull_request:
    branches:
    - master

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Sources
      uses: actions/checkout@v1
    - name: Lint Files
      uses: norio-nomura/action-swiftlint@3.2.1

