name: Tests

on:
  workflow_call:
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Sources
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '3.1'
    - name: Install mdl
      run: gem install mdl
    - name: Lint files
      run: mdl .
  unittests:
    runs-on: macOS-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Test Swift Framework
      run: xcodebuild -project Engine.xcodeproj
                      -scheme EngineTests test
  swiftlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Sources
      uses: actions/checkout@v1
    - name: Lint Files
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
          args: --strict
