name: Unit Tests

on:
  workflow_call:
  pull_request:
    branches:
    - master

jobs:
  unittests:
    runs-on: macOS-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Test Swift Framework
      run: xcodebuild -project Engine.xcodeproj
                      -scheme EngineTests test
        
